spring:
  datasource:
    url: jdbc:mysql://localhost:3307/study_iot?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  banner:
    location: classpath:banner.txt

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080